### ISSUE TITLE
No exception raised even if  I don't  use field 'BLOCK_INSPECTOR' in settings.py

### ISSUE THREAD

**Issue by leonardfrank** [grammy-jiang/scrapy-block-inspector#1]
Following the instruction, we're told that users should assign value,  which indicates the path of the function,  which tests if a single request is blocked, to field 'BLOCK_INSPECTOR' first in settings.
In my case, I ran my spider without setting field 'BLOCK_INSPECTOR', the spider got stuck after console showed that 'Enable Downloadermiddlewares:' part. I couldn't get any useful feedback.There was no exception or error raised.  
So here's my opinion, we should add a function to raise exceptions if it checks out there is no value assigned to field 'BLOCK_INSPECTOR'.

**Comment by grammy-jiang** [comment]
`BLOCK_INSPECTOR` will become the prerequisite setting in the next release.

Thanks for your issue.
